name: "Get branch name"
description: "Get current branch name"
outputs:
  branch:
    description: "The name of the current branch"
    value: ${{ steps.get-branch.outputs.branch }}
runs:
  using: "composite"
  steps:
    - id: get-branch
      run: |
        # Extract branch name
         BRANCH_NAME=${GITHUB_REF#refs/heads/}

         # set output variable accessible in the action
         echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
      shell: bash
